export const data = {
    products: [
        {
            id: '1',
            image: '/images/p1.png',
            name: 'Gulf Grouper',
            description: 'Mild with sweet taste and large chunky flakes. order by pound',
            orderBy: 'lb',
            price: 31.99,
            countInStock: 21,

        },
        {
            id: '2',
            image: '/images/p2.png',
            name: 'Red Snapper',
            description: 'Mild with a slightly sweet taste. order by pound',
            orderBy: 'lb',
            price: 31.99,
            countInStock: 21,
        },
        {
            id: '3',
            image: '/images/p3.png',
            name: 'Triple Tail',
            description: 'Slightly mild with a sweet taste. order by pound',
            orderBy: 'lb',
            price: 28.99,
            countInStock: 21,
        },
        {
            id: '4',
            image: '/images/p4.png',
            name: 'Wild Salmon',
            description: 'Robust with firm texture. order by pound',
            orderBy: 'lb',
            price: 18.99,
            countInStock: 21,
        },
        {
            id: '5',
            image: '/images/p5.png',
            name: 'Mahi Mahi',
            description: 'Mild and slightly sweet. order by pound',
            orderBy: 'lb',
            price: 24.99,
            countInStock: 21,
        },
        {
            id: '6',
            image: '/images/p6.png',
            name: 'Lane Snapper',
            description: 'Mild taste with a firm flaky texture. order by pound',
            orderBy: 'lb',
            price: 25.99,
            countInStock: 21,
        },


    ],
    shrimp: [
        {
            id: '7',
            image: '/images/s1.png',
            name: 'Peel N Eat - Medium',
            description: '21-25 shrimp per pound',
            orderBy: 'lb',
            price: 18.99,
            countInStock: 21,
        },
        {
            id: '8',
            image: '/images/s1.png',
            name: 'Peel N Eat - Jumbo',
            description: '10-15 shrimp per pound',
            orderBy: 'lb',
            price: 22.99,
            countInStock: 21,
        },
        {
            id: '9',
            image: '/images/s2.png',
            name: 'Mango BBQ Skewer',
            description: 'order by skewer',
            orderBy: 'skewer',
            price: 8,
            countInStock: 21,
        },
        {
            id: '10',
            image: '/images/s2.png',
            name: 'Teriyaki Skewer',
            description: 'order by skewer',
            orderBy: 'skewer',
            price: 8,
            countInStock: 21,
        },
        {
            id: '11',
            image: '/images/s2.png',
            name: 'Sweet Chili Skewer',
            description: 'order by skewer',
            orderBy: 'skewer',
            price: 8,
            countInStock: 21,
        },
        {
            id: '12',
            image: '/images/s3.png',
            name: 'Shrimp Ceviche - 1 Pint',
            description: 'order by pint',
            orderBy: 'pint',
            price: 22,
            countInStock: 21,
        },
        {
            id: '13',
            image: '/images/s3.png',
            name: 'Shrimp Ceviche - 1/2 Pint',
            description: 'order by 1/2 pint',
            orderBy: '1/2 pint',
            price: 13,
            countInStock: 1,
        },
    ],
    CrabAndShellfish: [
        {
            id: '14',
            image: '/images/c1.png',
            name: 'Fresh Crab Cakes',
            description: '1/4 lb individual patties , pairs well with Pirate Sauce',
            orderBy: ' ',
            price: 13,
            countInStock: 21,
        },
        {
            id: '15',
            image: '/images/c2.png',
            name: 'Stone Crab Claws',
            description: 'Available in Medium, Large & Jumbo. Market Price',
            orderBy: 'lb',
            price: '',
            countInStock: 21,
        },
        {
            id: '16',
            image: '/images/c3.png',
            name: 'Fresh Mussels. order by pounds',
            orderBy: 'lb',
            description: '',
            price: 9.99,
            countInStock: 21,
        },
        {
            id: '17',
            image: '/images/c4.png',
            name: 'Fresh Scallops',
            description: '10-20 per pound',
            orderBy: 'lb',
            price: 33.99,
            countInStock: 21,
        },
        {
            id: '18',
            image: '/images/c5.png',
            name: 'Live Clams - 100 count',
            description: 'Live middle neck clams.',
            orderBy: 'houndred',
            price: 33.99,
            countInStock: 21,
        },
        {
            id: '19',
            image: '/images/c5.png',
            name: 'Live Clams - Dozen',
            description: 'Live middle neck clams.',
            orderBy: 'dozen',
            price: 8,
            countInStock: 21,
        },
        {
            id: '20',
            image: '/images/c6.png',
            name: 'Oysters',
            description: '30 lb box of oysters',
            orderBy: 'box',
            price: 75,
            countInStock: 21,
        },
    ],
    SaucesandSalsa: [
        {
            id: '21',
            image: '/images/ss1.png',
            name: 'Cocktail Sauce',
            description: '8oz',
            orderBy: '',
            price: 6,
            countInStock: 21,
        },
        {
            id: '22',
            image: '/images/ss2.png',
            name: 'Tarter Sauce',
            description: '8oz',
            orderBy: '',
            price: 6,
            countInStock: 21,
        },
        {
            id: '23',
            image: '/images/ss3.png',
            name: 'Garlic Butter',
            description: '8oz',
            orderBy: '',
            price: 7,
            countInStock: 21,
        },
        {
            id: '24',
            image: '/images/ss4.png',
            name: 'Sweet Chili Sauce',
            description: '8oz',
            orderBy: '',
            price: 6,
            countInStock: 21,
        },
        {
            id: '25',
            image: '/images/s2.png',
            name: 'Pirate Sauce',
            description: '8oz',
            orderBy: '',
            price: 6,
            countInStock: 21,
        },
        {
            id: '26',
            image: '/images/s2.png',
            name: 'Pirate Sauce',
            description: '8oz',
            orderBy: '',
            price: 6,
            countInStock: 21,
        },
        {
            id: '27',
            image: '/images/ss5.png',
            name: 'Mango Salsa - 1 Pint',
            description: '',
            orderBy: '',
            price: 18,
            countInStock: 21,
        },
        {
            id: '28',
            image: '/images/ss5.png',
            name: 'Mango Salsa - 1/2 Pint',
            description: '',
            orderBy: '1/2 pint',
            price: 21,
            countInStock: 1,
        },
        {
            id: '29',
            image: '/images/ss6.png',
            name: 'Black Bean Salsa - 1 Pint',
            description: '',
            orderBy: 'pint',
            price: 18,
            countInStock: 21,
        },
        {
            id: '30',
            image: '/images/ss6.png',
            name: 'Black Bean Salsa - 1/2 Pint',
            description: '',
            orderBy: '1/2 pint',
            price: 21,
            countInStock: 1,
        },
    ],
    Seasoning: [
        {
            id: '31',
            image: '/images/seas1.png',
            name: 'Beer Batter',
            description: '',
            orderBy: '',
            price: 3.99,
            countInStock: 21,
        },
        {
            id: '32',
            image: '/images/seas2.png',
            name: 'Old Bay',
            description: '',
            orderBy: '',
            price: 3.99,
            countInStock: 21,
        },
        {
            id: '33',
            image: '/images/seas3.png',
            name: 'Chef Paul Blackening',
            description: '',
            orderBy: '',
            price: 5.50,
            countInStock: 21,
        },
        {
            id: '34',
            image: '/images/seas4.png',
            name: 'Panko Bread Crumbs',
            description: '',
            orderBy: '',
            price: 4.25,
            countInStock: 21,
        },
        {
            id: '35',
            image: '/images/seas5.png',
            name: 'Shrimp / Crab Boil',
            description: '',
            orderBy: '',
            price: 3.25,
            countInStock: 21,
        },
        {
            id: '36',
            image: '/images/seas6.png',
            name: 'Lemon Juice',
            description: '',
            orderBy: '',
            price: 2.29,
            countInStock: 21,
        },
        {
            id: '37',
            image: '/images/seas7.png',
            name: 'Fresh Lemon / Lime',
            description: '',
            orderBy: '',
            price: 1.25,
            countInStock: 21,
        },
    ],
    Special: [
        {
            id: '38',
            image: '/images/spes1.png',
            name: 'Gator Tail',
            description: 'Cubed',
            orderBy: '',
            price: 17,
            countInStock: 21,
        },
        {
            id: '39',
            image: '/images/spes2.png',
            name: 'Frog Legs',
            description: '4-6 per pound',
            orderBy: 'lb',
            price: 13.99,
            countInStock: 21,
        },
        {
            id: '40',
            image: '/images/spes3.png',
            name: 'Lobster Bisque - 1 Quart',
            description: '',
            orderBy: 'quart',
            price: 28,
            countInStock: 21,
        },
        {
            id: '41',
            image: '/images/spes3.png',
            name: 'Lobster Bisque - 1 Pint',
            description: '',
            orderBy: 'pint',
            price: 16,
            countInStock: 21,
        },
    ]
}