export const data = {
    products: [
        {
            id: '1',
            image: '/images/p1.png',
            name: 'Red Grouper',
            description: 'Mild with sweet taste and large chunky flakes. order by pound',
            orderBy: 'lb',
            price: 38.99,
            countInStock: 21,

        },
        {
            id: '2',
            image: '/images/p2.png',
            name: 'Red Snapper',
            description: 'Mild with a slightly sweet taste. order by pound',
            orderBy: 'lb',
            price: 38.99,
            countInStock: 21,
        },
        {
            id: '3',
            image: '/images/p6.png',
            name: 'Lane Snapper',
            description: 'Mild taste with a firm flaky texture. order by pound',
            orderBy: 'lb',
            price: 32.99,
            countInStock: 21,
        }, 
        {
            id: '4',
            image: '/images/p3.png',
            name: 'Triple Tail',
            description: 'Slightly mild with a sweet taste. order by pound',
            orderBy: 'lb',
            price: 31.99,
            countInStock: 21,
        },
        {
            id: '5',
            image: '/images/p5.png',
            name: 'Mahi Mahi',
            description: 'Mild and slightly sweet. order by pound',
            orderBy: 'lb',
            price: 26.95,
            countInStock: 21,
        },
        {
            id: '6',
            image: '/images/fishoftheweek.png',
            name: 'Fish of the Week',
            description: 'Ask what is on hand!',
            orderBy: '',
            price: 35.99,
            countInStock: 21,
        },
    ],
    shrimp: [
        {
            id: '7',
            image: '/images/s1.png',
            name: 'Peel N Eat - Large',
            description: '20-25 shrimp per pound',
            orderBy: 'lb',
            price: 19.99,
            countInStock: 21,
        },
        {
            id: '8',
            image: '/images/s1.png',
            name: 'Peel N Eat - Jumbo',
            description: '14-16 shrimp per pound',
            orderBy: 'lb',
            price: 22.99,
            countInStock: 21,
        },
        /*{
            id: '9',
            image: '/images/s2.png',
            name: 'Mango BBQ Skewer',
            description: 'order by skewer',
            orderBy: 'skewer',
            price: 8,
            countInStock: 21,
        },
        {
            id: '10',
            image: '/images/s2.png',
            name: 'Teriyaki Skewer',
            description: 'order by skewer',
            orderBy: 'skewer',
            price: 8,
            countInStock: 21,
        },
        {
            id: '11',
            image: '/images/s2.png',
            name: 'Sweet Chili Skewer',
            description: 'order by skewer',
            orderBy: 'skewer',
            price: 8,
            countInStock: 21,
        },
        {
            id: '12',
            image: '/images/s3.png',
            name: 'Shrimp Ceviche - 1 Pint',
            description: 'order by pint',
            orderBy: 'pint',
            price: 22,
            countInStock: 21,
        },
        {
            id: '13',
            image: '/images/s3.png',
            name: 'Shrimp Ceviche - 1/2 Pint',
            description: 'order by 1/2 pint',
            orderBy: '1/2 pint',
            price: 13,
            countInStock: 3,
        },
        {
            id: '14',
            image: '/images/shrimpCocktail.png',
            name: 'Jumbo Shrimp Cocktail',
            description: 'Individual serving',
            orderBy: '',
            price: 10.99,
            countInStock: 21,
        },  */
    ],
    CrabAndShellfish: [
        {
            id: '15',
            image: '/images/neck.png',
            name: 'Little Neck',
            description: 'Small 1.5-2" wide',
            orderBy: 'bag',
            price: 35,
            countInStock: 21,
        },
        {
            id: '16',
            image: '/images/neck.png',
            name: 'Medium Neck',
            description: 'Medium 2-2.5" wide',
            orderBy: 'bag',
            price: 40,
            countInStock: 21,
        }, {
            id: '17',
            image: '/images/neck.png',
            name: 'Top Neck',
            description: 'Large 2.5-3" wide',
            orderBy: 'bag',
            price: 45,
            countInStock: 21,
        },
        /*{
            id: '15',
            image: '/images/c1.png',
            name: 'Fresh Crab Cakes',
            description: '1/4 lb individual patties , pairs well with Pirate Sauce',
            orderBy: '',
            price: 13,
            countInStock: 21,
        },
        {
            id: '16',
            image: '/images/c2.png',
            name: 'Stone Crab Claws',
            description: 'Market Price',
            orderBy: 'lb',
            price: '',
            countInStock: 21,
        },
        {
            id: '17',
            image: '/images/c3.png',
            name: 'Fresh Mussels',
            description: 'order by pounds',
            orderBy: 'lb',
            price: 9.99,
            countInStock: 21,
        },*/
        {
            id: '18',
            image: '/images/boxoysters.png',
            name: 'Box of Oysters (40)',
            description: 'Box of 40',
            orderBy: 'box',
            price: 37,
            countInStock: 21,
        },
        {
            id: '19',
            image: '/images/boxoysters.png',
            name: 'Box of Oysters (70)',
            description: 'Box of 70',
            orderBy: 'box',
            price: 75,
            countInStock: 21,
        },
        {
            id: '20',
            image: '/images/individual.png',
            name: 'Individual',
            description: 'Individual, single pieces. Priced per piece',
            orderBy: 'box',
            price: 1.25,
            countInStock: 21,
        },
        {
            id: '201',
            image: '/images/shucked.png',
            name: 'Shucked Oysters (Half pint)',
            description: 'Shucked oysters, half pint',
            orderBy: 'box',
            price: 13,
            countInStock: 21,
        },
        {
            id: '202',
            image: '/images/shucked.png',
            name: 'Shucked Oysters (Pint)',
            description: 'Shucked oysters, pint',
            orderBy: 'box',
            price: 24,
            countInStock: 21,
        },
        {
            id: '203',
            image: '/images/snowcrab.png',
            name: 'Snow Crab',
            description: '2 clusters, about 3-4 legs',
            orderBy: '',
            price: 14.59,
            countInStock: 21,
        },
        {
            id: '204',
            image: '/images/stonecrab.png',
            name: 'Stone Crab',
            description: 'Available seasonally during the spring. Claws are sold at Market',
            orderBy: '',
            price: 1,
            countInStock: 21,
        },
        {
            id: '205',
            image: '/images/bluecrab.png',
            name: 'Blue Crab (Large Male)',
            description: 'Whole Blue crab. Sold by the dozen',
            orderBy: '',
            price: 45,
            countInStock: 21,
        },
        {
            id: '206',
            image: '/images/bluecrab.png',
            name: 'Blue Crab (Medium)',
            description: 'Whole Blue crab. Sold by the dozen',
            orderBy: '',
            price: 20,
            countInStock: 21,
        },
        {
            id: '207',
            image: '/images/crabcake.png',
            name: 'Crab Cakes',
            description: '1/4 lb patty, sold individually',
            orderBy: '',
            price: 8,
            countInStock: 21,
        },
        {
            id: '208',
            image: '/images/crabmushroom.png',
            name: 'Crab Stuffed Mushrooms',
            description: 'Priced per pound',
            orderBy: 'lb',
            price: 32,
            countInStock: 21,
        },
        {
            id: '209',
            image: '/images/scallops.png',
            name: 'Scallops',
            description: 'About 15 per pound',
            orderBy: 'lb',
            price: 32,
            countInStock: 21,
        },
        {
            id: '210',
            image: '/images/lobstertail.png',
            name: 'Lobster Tail',
            description: 'Sold by the pound',
            orderBy: 'lb',
            price: 30,
            countInStock: 21,
        },
    ],
    SeasonedButters: [
        {
            id: '211',
            image: '/images/delivery.png',
            name: 'Herb & Lemon',
            description: '8oz',
            orderBy: '',
            price: 2,
            countInStock: 21,
        },
        {
            id: '212',
            image: '/images/delivery.png',
            name: 'Cilantro Lime',
            description: '8oz',
            orderBy: '',
            price: 2,
            countInStock: 21,
        },
        {
            id: '213',
            image: '/images/delivery.png',
            name: 'Lemon Caper',
            description: '8oz',
            orderBy: '',
            price: 2,
            countInStock: 21,
        },
        {
            id: '214',
            image: '/images/delivery.png',
            name: 'Parsley, Chili & Garlic',
            description: '8oz',
            orderBy: '',
            price: 2,
            countInStock: 21,
        },
    ],
    Dips: [
        {
            id: '215',
            image: '/images/smokedmullet.png',
            name: 'Smoked Mullet',
            description: 'Smoked local mullet, 8oz',
            orderBy: '',
            price: 10.95,
            countInStock: 21,
        },
        {
            id: '216',
            image: '/images/salmon.png',
            name: 'Smoked Salmon',
            description: '8oz',
            orderBy: '',
            price: 10.95,
            countInStock: 21,
        },
        {
            id: '217',
            image: '/images/smokedshrimp.png',
            name: 'Smoked Shrimp',
            description: 'Smoked local shrimp, 8oz',
            orderBy: '',
            price: 10.95,
            countInStock: 21,
        },
        {
            id: '218',
            image: '/images/dipweek.png',
            name: 'Smoked Fish',
            description: 'This dip of the week has a changing selection. Ask us what we have for the week! 8oz',
            orderBy: '',
            price: 10.95,
            countInStock: 21,
        },
        {
            id: '219',
            image: '/images/bluecrabdip.png',
            name: 'Blue Crab',
            description: '8oz',
            orderBy: '',
            price: 10.95,
            countInStock: 21,
        },
    ],
    SaucesandSalsa: [
        {
            id: '21',
            image: '/images/cocktail.png',
            name: 'Cocktail ',
            description: '8oz',
            orderBy: '',
            price: 5.5,
            countInStock: 21,
        },
        {
            id: '22',
            image: '/images/tarter.png',
            name: 'Tartar',
            description: '8oz',
            orderBy: '',
            price: 6,
            countInStock: 21,
        },
        {
            id: '23',
            image: '/images/coleslaw.png',
            name: 'Coleslaw',
            description: '8oz',
            orderBy: '',
            price: 5,
            countInStock: 21,
        },
        /*
        {
            id: '24',
            image: '/images/ss4.png',
            name: 'Sweet Chili Sauce',
            description: '8oz',
            orderBy: '',
            price: 6,
            countInStock: 21,
        },
        {
            id: '25',
            image: '/images/s2.png',
            name: 'Pirate Sauce',
            description: '8oz',
            orderBy: '',
            price: 6,
            countInStock: 21,
        },
        {
            id: '26',
            image: '/images/ss5.png',
            name: 'Mango Salsa - 1 Pint',
            description: '',
            orderBy: 'pint',
            price: 18,
            countInStock: 21,
        },
        {
            id: '27',
            image: '/images/ss5.png',
            name: 'Mango Salsa - 1/2 Pint',
            description: '',
            orderBy: '1/2 pint',
            price: 10,
            countInStock: 3,
        },
        {
            id: '28',
            image: '/images/ss6.png',
            name: 'Black Bean Salsa - 1 Pint',
            description: '',
            orderBy: 'pint',
            price: 18,
            countInStock: 21,
        },
        {
            id: '29',
            image: '/images/ss6.png',
            name: 'Black Bean Salsa - 1/2 Pint',
            description: '',
            orderBy: '1/2 pint',
            price: 10,
            countInStock: 3,
        },*/
    ],
    Seasoning: [
        {
            id: '30',
            image: '/images/seafoodseasoning.png',
            name: 'J.O. Seafood Seasoning',
            description: '',
            orderBy: '',
            price: 8.50,
            countInStock: 21,
        },
        {
            id: '301',
            image: '/images/crabseasoning.png',
            name: 'J.O. Crab Seasoning',
            description: '',
            orderBy: '',
            price: 8.50,
            countInStock: 21,
        },
        {
            id: '31',
            image: '/images/everglades.png',
            name: 'Everglades Seasoning',
            description: '',
            orderBy: '',
            price: 4.25,
            countInStock: 21,
        },
        {
            id: '32',
            image: '/images/evergladeschicken.png',
            name: 'Everglades Fish & Chicken ',
            description: '',
            orderBy: '',
            price: 5.50,
            countInStock: 21,
        },
        {
            id: '33',
            image: '/images/delivery.png',
            name: 'Blackening',
            description: '',
            orderBy: '',
            price: 9.85,
            countInStock: 21,
        },
        {
            id: '34',
            image: '/images/delivery.png',
            name: 'Breading',
            description: '',
            orderBy: '',
            price: 4.50,
            countInStock: 21,
        },
        {
            id: '36',
            image: '/images/seas7.png',
            name: 'Fresh Lemon / Lime',
            description: '',
            orderBy: '',
            price: 1.25,
            countInStock: 21,
        },
    ],
    Special: [
    
        {
            id: '39',
            image: '/images/keylime.png',
            name: 'Karens Key Lime Pie',
            description: 'Serves about 4-6',
            orderBy: '',
            price: 20,
            countInStock: 21,
        },
       
    ]
}
